title: Leonardo's Wall
email: leointhecode@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Explore with Leo tand d iscover insights on software testing, career development, and the pursuit of a balanced lifestyle.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://leonardespi.me" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title/

twitter:
  username: leonardespii
  card: Senior QA engineer, athlete, and artist
github_username:  leonardespi

author: 
  name: Leonardo Espinosa
  url: https://www.leonardespi.me

social:
  name: Leonardo Espinosa
  links: 
    - https://x.com/leonardespii
    - https://www.linkedin.com/in/leonardespi/
    - https://www.instagram.com/leonardespi/
    - https://github.com/leonardespi

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
