#-------------------------------
# Site Settings
title: Leonardo Espinosa
description: leonardespi is an SDET and musician.
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: light # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Music'
      url: '/music/'
    - title: 'Posts'
      url: '/posts/' 
    - url: '/bio/'
      title: 'Bio'
    - url: '/contact/'
      title: 'Contact'
#    - url: '/elements/'
#      title: 'Elements'


#-------------------------------
# Author Settings
author:
  author_name: Leonardo Espinosa
  author_avatar: /images/pp-forest.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/pp-forest.jpg
  hero_title: I'm Leo 游녦
  hero_subtitle: SDET, musician and productivity obsessed
  hero_description: |
    This blog is my spot to share and connect. 
    
    Is constantly under construction like me.
  hero_image: /images/desktop-forest.jpg
  hero_image_caption: My studio is the most important room in the house.
  hero_button_text: Work with me
  hero_button_link: '/contacto/'


# Logos
logos:
  enable: false
  logos_title: Nerd Stuff
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: false
  blog_title: Bit치cora de Ideas


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  tags_section_title: My favorite stories
  tags:
    - tag: "Quality-Assurance"
      image: "/images/02-1.jpg"
    - tag: "Art"
      image: "/images/09-5.jpg"
    - tag: "Music"
      image: "/images/08-1.jpg"
    - tag: "Projects"
      image: "/images/03-1.jpg"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: My music


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: false
  gallery_section_title: Fotos cool que tome
  gallery:
    gallery_images:
      - alt: 'Edificios'
        url: '/images/09-1.jpg'
        caption: 'La ciudad a veces parece que te devora'
      - alt: 'Paisaje'
        url: '/images/09-2.jpg'
        caption: 'Un bello amanecer despues de madrugar'
      - alt: 'Pensamientos'
        url: '/images/09-3.jpg'
        caption: 'Es importante que exista un balance'
      - alt: 'Iglesia'
        url: '/images/09-4.jpg'
        caption: 'La primera foto que tome con mi c치mara.'
      - alt: 'Games'
        url: '/images/09-5.jpg'
        caption: 'No temas a la ca칤da; hasta la rueda m치s alta toca el suelo antes de volver a elevarse.'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Inspirate un ratito 九껊잺
  mailchimp_description: Todos los domingos env칤o a tu correo reflexiones, temas de arte, programaci칩n y productividad.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Tu direcci칩n de correo...
  mailchimp_button_text: 칔nete ya


#-------------------------------
# Footer Settings
footer_description: Check my socials to get bonus points on life.
#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/leonardespi/"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/leonardespi/"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://mastodon.social"}
- {icon: "fa-brands fa-spotify", name: "Spotify", link: "https://open.spotify.com/artist/67kVWiSDdKYabOPrqfO0Kr?si=ltP6pGnUTXahWsmsrw0LCQ"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/leonardespi"}
#- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: leointhecode@email.com # Add your form_id
  button_text: Send now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Inicia una conversaci칩n
  disqus_button_text: Mostrar los comentarios


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id